- ios/Classes/Plugin/PluginController.swift
- ios/Classes/Plugin/PluginError.swift
> Allow plug-in reinitialization on iOS

- android/src/main/kotlin/com/signify/hue/flutterreactiveble/channelhandlers/ScanDevicesHandler.kt
I find this log to be very spammy.
Please consider either removing it (this pull request) or provide (or document) a way to configure the log level.
> Remove "Device found" log

- .gitignore
- example/lib/main.dart
- example/lib/src/ble/ble_device_connector.dart
- example/lib/src/ble/ble_scanner.dart
- example/lib/src/ble/ble_status_monitor.dart
- example/lib/src/ble/reactive_state.dart
- example/lib/src/ui/ble_status_screen.dart
- example/lib/src/ui/device_detail_screen.dart
- example/lib/src/ui/device_list.dart
- example/pubspec.lock
- example/pubspec.yaml
- example/test/app_test.dart
- example/test/example_test.dart
- pubspec.lock
> Improve architecture example app

- CHANGELOG.MD
- README.md
- android/src/main/kotlin/com/signify/hue/flutterreactiveble/ble/BleClient.kt
- android/src/main/kotlin/com/signify/hue/flutterreactiveble/ble/BleWrapper.kt
- android/src/main/kotlin/com/signify/hue/flutterreactiveble/ble/ReactiveBleClient.kt
- android/src/main/kotlin/com/signify/hue/flutterreactiveble/channelhandlers/ScanDevicesHandler.kt
- android/src/main/kotlin/com/signify/hue/flutterreactiveble/utils/BleWrapperExtensions.kt
- example/lib/src/ble/ble_scanner.dart
- example/lib/src/ui/ble_status_screen.dart
- example/lib/src/ui/device_list.dart
- example/pubspec.lock
- example/pubspec.yaml
- ios/Classes/BleData/bledata.pb.swift
- ios/Classes/Plugin/PluginController.swift
- lib/src/generated/bledata.pb.dart
- lib/src/generated/bledata.pbjson.dart
- lib/src/model/ble_status.dart
- lib/src/model/scan_session.dart
- lib/src/prescan_connector.dart
- lib/src/reactive_ble.dart
- protos/Readme.md
- protos/bledata.proto
- pubspec.yaml
- test/prescan_connector_test.dart
- test/select_from_test.dart
> Support blescan with empty filter

- CHANGELOG.MD
- example/lib/src/ui/device_detail_screen.dart
- example/pubspec.lock
- pubspec.lock
- pubspec.yaml
- test/prescan_connector_test.dart
In order to add this plugin to https://github.com/flutter/tests I need to fix a test in prescan_connector_test.dart. 
While doing this I added a couple of commits to fix analyzer issues and pub spec.yaml cleanup.
> Minor fixes

- lib/src/discovered_devices_registry.dart
- lib/src/model/ble_status.dart
- lib/src/reactive_ble.dart
- test/discovered_devices_registry_test.dart
@werediver this is a temp PR to use for discussion on the style of documenting and the amount of information we should provide. 
I was a bit struggling so hopefully you can help out.
> improve dartdoc for reactive_ble

- lib/src/model/ble_status.dart
- lib/src/model/characteristic_value.dart
- lib/src/model/clear_gatt_cache_error.dart
- lib/src/model/connection_priority.dart
- lib/src/model/connection_state_update.dart
- lib/src/model/discovered_device.dart
- lib/src/model/generic_failure.dart
- lib/src/model/qualified_characteristic.dart
- lib/src/model/result.dart
- lib/src/model/scan_mode.dart
- lib/src/reactive_ble.dart
Added docs to most publicly exposed files. 
@werediver  only the uuid, repeater and serialdisposable need to be done. Maybe you can pick that up in a separate pr.
> Finalise docs reactive ble

- CHANGELOG.md
- example/ios/Runner.xcodeproj/project.pbxproj
- example/ios/Runner.xcworkspace/xcshareddata/WorkspaceSettings.xcsettings
- example/pubspec.lock
- example/pubspec.yaml
- pubspec.lock
- pubspec.yaml
from flutter 1..17 and onwards this is needed. 1.17 is going to become stable soon
> update packages and pubspec structure to comply to new standards

- lib/src/reactive_ble.dart
Useage of autoconnect was not clear in the docs.  Issue #58 triggered me on improving the docs
> add additional explanation about effect of no connection timeout

- example/lib/src/widgets.dart
- lib/src/model/scan_mode.dart
- lib/src/model/uuid.dart
- lib/src/rx_ext/repeater.dart
- lib/src/rx_ext/serial_disposable.dart
Fixes #61  
@werediver  please advise about repeater definition since I struggled with that one
> Improve doc comments

- lib/src/converter/args_to_protubuf_converter.dart
- lib/src/converter/protobuf_converter.dart
- lib/src/device_connector.dart
- lib/src/device_scanner.dart
- lib/src/plugin_controller.dart
- lib/src/reactive_ble.dart
- test/converter/args_to_protobuf_converter_test.dart
- test/converter/protobuf_converter_test.dart
- test/device_connector_test.dart
- test/device_scanner_test.dart
- test/plugin_controller_test.dart
moved last logic out of the facade. Next pr I will test the facade itself. At the moment test coverage is up to 59% .
> Move remaining logic out of ble facade

- example/pubspec.lock
- lib/src/device_scanner.dart
- pubspec.lock
- pubspec.yaml
- test/device_scanner_test.dart
> fix propagating stream error in devicescanner

- CHANGELOG.md
- example/pubspec.yaml
- lib/src/converter/args_to_protubuf_converter.dart
- lib/src/reactive_ble.dart
- pubspec.yaml
- test/converter/args_to_protobuf_converter_test.dart
- test/reactive_ble_test.dart
@werediver  we now have 90% code coverage over the non generated classes. The  remaining 10% would be "silly" tests to check if assert != null is working and test toString methods from the model. Let's not do this :)
> Unittest reactive ble

- android/build.gradle
- android/src/main/kotlin/com/signify/hue/flutterreactiveble/PluginController.kt
- android/src/main/kotlin/com/signify/hue/flutterreactiveble/ReactiveBlePlugin.kt
- android/src/main/kotlin/com/signify/hue/flutterreactiveble/ble/DeviceConnector.kt
- android/src/main/kotlin/com/signify/hue/flutterreactiveble/ble/ReactiveBleClient.kt
- android/src/main/kotlin/com/signify/hue/flutterreactiveble/channelhandlers/BleStatusHandler.kt
- android/src/main/kotlin/com/signify/hue/flutterreactiveble/channelhandlers/CharNotificationHandler.kt
- android/src/main/kotlin/com/signify/hue/flutterreactiveble/channelhandlers/DeviceConnectionHandler.kt
- android/src/main/kotlin/com/signify/hue/flutterreactiveble/channelhandlers/ScanDevicesHandler.kt
- example/lib/src/ui/device_list.dart
- lib/flutter_reactive_ble.dart
- lib/src/debug_logger.dart
- lib/src/model/log_level.dart
- lib/src/plugin_controller.dart
- lib/src/reactive_ble.dart
- test/debug_logger_test.dart
- test/plugin_controller_test.dart
- test/reactive_ble_test.dart
Proposal for having consistent logging on iOS and Android.
- Removed Android logging
- Added a debugLogger
- Added logs for the plugincontroller (this one makes the most sense in my opinion). For the result we provide useful errors.
> Consistent logging

- CHANGELOG.md
- android/src/main/kotlin/com/signify/hue/flutterreactiveble/channelhandlers/CharNotificationHandler.kt
- example/pubspec.lock
- pubspec.yaml
#92 revealed some in proper error handling on the notifications.
Fixes #97
> fix for crash on notifications when device gets disconnected

- android/src/main/kotlin/com/signify/hue/flutterreactiveble/ble/ReactiveBleClient.kt
> use scanrecord instead of ble devie

- ios/flutter_reactive_ble.podspec
- pubspec.yaml
> Update podspec (iOS/CocoaPods configuration)

- android/build.gradle
- example/android/build.gradle
- example/android/gradle.properties
- example/android/gradle/wrapper/gradle-wrapper.properties
> upgrade android dependencies

- CHANGELOG.md
- android/src/main/kotlin/com/signify/hue/flutterreactiveble/channelhandlers/ScanDevicesHandler.kt
- example/pubspec.lock
- example/pubspec.yaml
- pubspec.yaml
> Fix issue devicescan android on hot restart

- example/pubspec.yaml
- pubspec.yaml
The sort_pub_dependencies lint is currently broken, but soon will be fixed.
This fixes the sorting if the pubspec here in preparation for that fix.
/cc @pq
> Fix pubspec sorting

- CHANGELOG.md
- android/src/main/kotlin/com/signify/hue/flutterreactiveble/ble/DeviceConnector.kt
- android/src/main/kotlin/com/signify/hue/flutterreactiveble/ble/ReactiveBleClient.kt
- android/src/main/kotlin/com/signify/hue/flutterreactiveble/channelhandlers/DeviceConnectionHandler.kt
- android/src/test/kotlin/com/signify/hue/flutterreactiveble/ble/DeviceConnectorTest.kt
- example/pubspec.lock
- example/pubspec.yaml
- pubspec.yaml
> emit disconnected state update when device gets disconnected

- example/lib/src/ui/device_detail_screen.dart
- example/lib/src/ui/device_list.dart
Replaced obsolete references to RaisedButton with ElevatedButton per flutter/flutter#59702.
> Replaced RaisedButton with ElevatedButton

- ios/flutter_reactive_ble.podspec
- lib/flutter_reactive_ble.dart
- lib/src/converter/protobuf_converter.dart
- lib/src/model/discovered_service.dart
- lib/src/model/discovered_service.g.dart
- lib/src/plugin_controller.dart
- lib/src/reactive_ble.dart
- test/converter/protobuf_converter_test.dart
- test/plugin_controller_test.dart
- test/reactive_ble_test.dart
> Export `DiscoveredService` class

- ios/Classes/ReactiveBle/Central.swift
- lib/src/connected_device_operation.dart
- lib/src/plugin_controller.dart
- lib/src/reactive_ble.dart
- test/plugin_controller_test.dart
Fixes #137
Also corrects an error message mentioned in #138. @HelloBytes Thank you for uncovering it!
> Initialize event channels early

- CHANGELOG.md
- android/build.gradle
- example/android/app/build.gradle
- example/pubspec.lock
- example/pubspec.yaml
- pubspec.yaml
> Lower minsdk android

- CHANGELOG.md
- android/build.gradle
- example/pubspec.lock
- example/pubspec.yaml
- ios/Classes/BleData/bledata.pb.swift
- lib/src/generated/bledata.pb.dart
- lib/src/generated/bledata.pbenum.dart
- lib/src/generated/bledata.pbjson.dart
- lib/src/generated/bledata.pbserver.dart
- pubspec.yaml
Fix for  #115. Also saw that our pub.dev score was lower because we used older version of protobuf generated code
> Fix protobuf issues

- android/build.gradle
- android/proguard-rules.txt
> add custom proguard file to reactive ble lib

- example/pubspec.lock
- example/pubspec.yaml
- lib/src/connected_device_operation.dart
- lib/src/converter/args_to_protubuf_converter.dart
- lib/src/converter/protobuf_converter.dart
- lib/src/debug_logger.dart
- lib/src/device_connector.dart
- lib/src/device_scanner.dart
- lib/src/discovered_devices_registry.dart
- lib/src/plugin_controller.dart
- lib/src/reactive_ble.dart
- pubspec.lock
- pubspec.yaml
- test/connected_device_operation_test.dart
- test/converter/args_to_protobuf_converter_test.dart
- test/converter/protobuf_converter_test.dart
- test/debug_logger_test.dart
- test/device_connector_test.dart
- test/device_scanner_test.dart
- test/discovered_devices_registry_test.dart
- test/plugin_controller_test.dart
- test/reactive_ble_test.dart
- test/result_test.dart
- test/rx_ext/repeater_test.dart
- test/rx_ext/serial_disposable_test.dart
- test/stubs/device_scanner_stub.dart
@werediver I  moved towards stubs and extracted interfaces without compromising our test coverage.
> Do not use mockito

- android/src/main/kotlin/com/signify/hue/flutterreactiveble/ble/ReactiveBleClient.kt
> add simple fix to determine mode when subscribing on android

- CHANGELOG.md
- android/build.gradle
- example/android/app/build.gradle
- example/android/build.gradle
- example/android/gradle/wrapper/gradle-wrapper.properties
- example/pubspec.lock
- example/pubspec.yaml
- pubspec.yaml
> upgrade android dependencies to comply to newer gradle distributions

- android/src/main/kotlin/com/signify/hue/flutterreactiveble/converters/ProtobufMessageConverter.kt
Fix #209
I really do not know why I made it before like this it drives me nuts this part of the code. Really need some time to refactor things there
> fix bug in uuid conversion on android

- CHANGELOG.md
- android/build.gradle
- android/src/main/kotlin/com/signify/hue/flutterreactiveble/channelhandlers/ScanDevicesHandler.kt
- android/src/main/kotlin/com/signify/hue/flutterreactiveble/converters/ProtobufMessageConverter.kt
- example/android/app/build.gradle
- example/android/build.gradle
- example/android/gradle/wrapper/gradle-wrapper.properties
- example/ios/Flutter/Debug.xcconfig
- example/ios/Flutter/Release.xcconfig
- example/ios/Podfile.lock
- example/ios/Runner.xcodeproj/project.pbxproj
- example/ios/Runner.xcodeproj/project.xcworkspace/contents.xcworkspacedata
- example/pubspec.lock
- example/pubspec.yaml
- pubspec.lock
- pubspec.yaml
@werediver  let's ship the first version. After this I want to extend the example app with read and write and subscribe (only for null safe) which would help us in triaging bugs and improving the API's from there. 
- Part of this pr is rebase from master
-  The following commits are new: [link1](https://github.com/PhilipsHue/flutter_reactive_ble/pull/225/commits/8c5ae7149d6d2035db660a88b7cbb8b8a6cffee5) [link2](https://github.com/PhilipsHue/flutter_reactive_ble/pull/225/commits/90d463f78d7fe718bc26c58294a14fc26a24dea1)
> Upgrade null safety to latest flutter stable

- android/src/main/kotlin/com/signify/hue/flutterreactiveble/ble/ReactiveBleClient.kt
- android/src/test/kotlin/com/signify/hue/flutterreactiveble/ble/ReactiveBleClientTest.kt
Same as  #229 but then null-safety
> do not discover services when bonding is in progress [null-safety]

- CHANGELOG.md
- android/build.gradle
- android/src/main/kotlin/com/signify/hue/flutterreactiveble/ble/ReactiveBleClient.kt
- example/android/app/build.gradle
- example/android/build.gradle
- example/android/gradle/wrapper/gradle-wrapper.properties
- example/pubspec.lock
- example/pubspec.yaml
- pubspec.yaml
> Fix issues fb connectivity in bg

- CHANGELOG.md
- android/src/main/kotlin/com/signify/hue/flutterreactiveble/channelhandlers/CharNotificationHandler.kt
- example/pubspec.lock
- example/pubspec.yaml
- pubspec.yaml
> move disposable into companion object so they survive isolate creation

- ios/Classes/Plugin/PluginController.swift
same behavior as Android
fix #183 
@werediver  I started learning Swift recently so not sure if this is what you also had in mind
> assume connecting state on iOS

- packages/reactive_ble_mobile/android/src/main/kotlin/com/signify/hue/flutterreactiveble/ReactiveBlePlugin.kt
- packages/reactive_ble_mobile/pubspec.lock
- packages/reactive_ble_mobile/pubspec.yaml
> Upgrade flutter for reactive_ble_mobile and remove deprecated embedding function

- packages/reactive_ble_mobile/ios/Classes/Plugin/PluginController.swift
- packages/reactive_ble_mobile/ios/Classes/Plugin/SwiftReactiveBlePlugin.swift
Queue up messages until event-sink has been created
Closes #307, #251, #137, #387
> ios: Queue up messages

- example/pubspec.lock
- example/pubspec.yaml
Currently it seems to be pulling the version from pub.dev.
> Ensure the example is built against the local version of reactive_ble_mobile

- example/pubspec.lock
- example/pubspec.yaml
- packages/flutter_reactive_ble/CHANGELOG.md
- packages/flutter_reactive_ble/pubspec.lock
- packages/flutter_reactive_ble/pubspec.yaml
- packages/reactive_ble_mobile/CHANGELOG.md
- packages/reactive_ble_mobile/ios/Classes/Plugin/PluginController.swift
- packages/reactive_ble_mobile/ios/Classes/Plugin/SwiftReactiveBlePlugin.swift
- packages/reactive_ble_mobile/pubspec.lock
- packages/reactive_ble_mobile/pubspec.yaml
- packages/reactive_ble_platform_interface/CHANGELOG.md
- packages/reactive_ble_platform_interface/pubspec.yaml
@werediver  I couldn't find why it didn't work but I know that all issues with reconnection and discovery are gone once I revert this change (was easy to reproduce at home). Fixes:  #439 
This reverts commit 60f292f20633b1e3cc28fdeabaf9b698b626447b, reversing
changes made to 51349d8c10cb40bfd9c73aaae3cceca52bcf8587.
> Revert "Merge pull request #406 from plyobits/queue_messages"

- README.md
> Add kotlin version to readme

- bin/quality_checks.sh
- example/pubspec.lock
- packages/flutter_reactive_ble/lib/src/connected_device_operation.dart
- packages/flutter_reactive_ble/lib/src/device_scanner.dart
- packages/flutter_reactive_ble/pubspec.lock
- packages/flutter_reactive_ble/test/reactive_ble_test.dart
- packages/reactive_ble_mobile/pubspec.lock
- packages/reactive_ble_mobile/test/converter/protobuf_converter_test.dart
- packages/reactive_ble_mobile/test/reactive_ble_platform_test.dart
- packages/reactive_ble_platform_interface/lib/src/model/discovered_device.dart
- packages/reactive_ble_platform_interface/pubspec.lock
This fisx quality checks monorepo on codemagic 
I found a similar issue here  [melos](https://github.com/invertase/melos/issues/209)
> Fix quality checks monorepo

- packages/reactive_ble_mobile/android/src/main/kotlin/com/signify/hue/flutterreactiveble/ble/ReactiveBleClient.kt
- packages/reactive_ble_mobile/android/src/main/kotlin/com/signify/hue/flutterreactiveble/converters/ManufacturerDataConverter.kt
> Add additional null checks to scanRecord

- README.md
Spent some time with this library and documented some simple examples. Hope it could be helpful to others getting started.
> unofficial example app proposal

- example/android/app/src/main/AndroidManifest.xml
- example/pubspec.lock
- example/pubspec.yaml
- packages/flutter_reactive_ble/CHANGELOG.md
- packages/flutter_reactive_ble/pubspec.lock
- packages/flutter_reactive_ble/pubspec.yaml
- packages/reactive_ble_mobile/CHANGELOG.md
- packages/reactive_ble_mobile/pubspec.lock
- packages/reactive_ble_mobile/pubspec.yaml
- packages/reactive_ble_platform_interface/CHANGELOG.md
- packages/reactive_ble_platform_interface/pubspec.lock
- packages/reactive_ble_platform_interface/pubspec.yaml
@werediver @PieterAelse , can you please review this so we can release new version!
> bump version 5.0.3

- bin/flutter_customer_test.bat
- bin/flutter_customer_test.sh
See https://github.com/flutter/tests/blob/main/registry/flutter_reactive_ble.test
> Add a script for running tests (intended for use by the Flutter customer tests repository)

- packages/flutter_reactive_ble/pubspec.lock
- packages/reactive_ble_mobile/pubspec.lock
- packages/reactive_ble_platform_interface/pubspec.lock
> Include packages lock-files

- analysis_options.yaml
- example/lib/src/ble/ble_device_connector.dart
- example/lib/src/ble/ble_scanner.dart
- example/pubspec.lock
- example/pubspec.yaml
- packages/flutter_reactive_ble/lib/src/rx_ext/serial_disposable.dart
- packages/reactive_ble_mobile/pubspec.lock
- packages/reactive_ble_mobile/pubspec.yaml
> Migrate away from deprecated strong mode analysis options
