PhilipsHue/flutter_reactive_ble

- README.md
- android/src/main/kotlin/com/signify/hue/flutterreactiveble/PluginController.kt
people that use library themselves should implement custom rx handler. Since it is a singleton we do not want to possibly override customhandlers
> remove rxjava errorhandler

- example/ios/Runner/Info.plist
The usage description keys for Bluetooth are required since iOS 13 (I think). Without them, the sample app crashes immediately.
Resolves #14.
> Add iOS Bluetooth usage description keys in the sample app

- pubspec.lock
- pubspec.yaml
It seems that I cleaned-up a bit too much in my previous PR, although nothing (pub get, analyzer or tests) hinted that there was an issue.
It seems that we can't remove the flutter dependency from the package, even when it doesn't seem to depend on it... Now I can that it was a wrong assumption: tooling relies on it apparently.
Anyway, this could have been caught by running `flutter pub publish --dry-run`.
@remonh87, maybe you can add a step in the PR qualification pipeline to run this command.
> Revert removal of flutter dependency in root pubspec.yaml

- ios/Classes/ReactiveBle/Central.swift
This commit fixes a problem when iOS devices try to write a value to characteristics, which have only a type of .writeWithoutResponse.
> Bugfix: check for correct property when trying to write w/o response

- README.md
Create a small pr to add BLE status to readme since it is core functionality and it was not clear we support this main use case.
Fixes #51
> add ble status usage to readme

- lib/src/plugin_controller.dart
if we do not do this the event channel sctream will initialized over and over again which results in disconnections for no reason
> initialize eventchannels lazy

- ios/Classes/Plugin/PluginController.swift
> Prefer CBAdvertisementDataLocalName over peripheral.name

- README.md
I think this will be very helpful since proguard removes a lot of our generated code now and users can run into weird errors
> Add proguard rule to lib readme faq section

- android/src/main/kotlin/com/signify/hue/flutterreactiveble/channelhandlers/BleStatusHandler.kt
I see this error in crashlytics:
```
Caused by java.lang.IllegalArgumentException
Unsupported value: [Ljava.lang.StackTraceElement;@d0a315d
io.flutter.plugin.common.StandardMessageCodec.a
io.flutter.plugin.common.StandardMessageCodec.a (StandardMessageCodec.java:392)
io.flutter.plugin.common.StandardMethodCodec.a (StandardMethodCodec.java:37)
io.flutter.plugin.common.EventChannel$IncomingStreamRequestHandler$EventSinkImplementation.a (EventChannel.java:45)
com.signify.hue.flutterreactiveble.channelhandlers.BleStatusHandler$listenToBleStatus$3.accept (BleStatusHandler.java:17)
com.signify.hue.flutterreactiveble.channelhandlers.BleStatusHandler$listenToBleStatus$3.accept (BleStatusHandler.java:2)
io.reactivex.internal.observers.LambdaObserver.a (LambdaObserver.java:13) …
```
> Don't pass stackTrace in EventSink.error

- README.md
Hello
@werediver @remonh87, as a follow up of https://github.com/PhilipsHue/flutter_reactive_ble/issues/170, and pull request https://github.com/PhilipsHue/flutter_reactive_ble/pull/178, I created a repository containing the example.
As a reminder, I created this pull request adding an reference to it in the READ.md file. I'm happy to receive review comments on this example.
Br
Carl.
> added reference to external example flutter app

- CHANGELOG.md
- android/src/main/kotlin/com/signify/hue/flutterreactiveble/channelhandlers/ScanDevicesHandler.kt
- example/pubspec.lock
- example/pubspec.yaml
- pubspec.yaml
There is nothing wrong with the previous code however for some weird reason firebase resets state of the eventchannels which looks really fishy. Also there are quite some bugs there. This workaround however makes sense and guarantees good functioning state.
Fixes #195
> fix reinitializing of the eventchannel scanparameter by firebase

- android/src/main/kotlin/com/signify/hue/flutterreactiveble/ble/ReactiveBleClient.kt
- android/src/test/kotlin/com/signify/hue/flutterreactiveble/ble/ReactiveBleClientTest.kt
While dicovering services can result in interfering bonding using the just works principle as stated in: https://medium.com/@martijn.van.welie/making-android-ble-work-part-4-72a0b85cb442
> do not discover services when bonding is in progress

- lib/src/reactive_ble.dart
This pull-requests is built on top of #218 to further improve wording in the documentation of `conectToDevice` and `connectToAdvertisingDevice` methods.
Relates to #215.
> Update doc-comments for `conectToDevice` and `connectToAdvertisingDevice`

- test/connected_device_operation_test.dart
- test/converter/args_to_protobuf_converter_test.dart
- test/converter/protobuf_converter_test.dart
- test/device_scanner_test.dart
In each library where an import is removed, the library uses some elements
provided by the import, BUT there is another import which provides all of the
same elements, and at least one more which the library uses.
In this change, we remove the imports which can be simply removed in favor of
the other already present imports.
See https://github.com/dart-lang/sdk/issues/44569 for more information.
> Remove "unnecessary" imports.

- README.md
> add ensuring ble stack ready to readme

- example/pubspec.yaml
Done because version 2 depends on args ^1.5.0, which conflicts with dbus.dart which required ^2.0.0
> Bump dependency of dependency_validator

- README.md
- packages/reactive_ble_mobile/ios/Classes/Prelude/CoreBluetooth+Extensions.swift
Hi! This PR makes `flutter_reactive_ble` buildable and workable both in Xcode 12 and Xcode 13, which I would appreciate since our team not planning to migrate CI/CD to Xcode 13 for at least a couple of months. Thanks.
> Restore support for Xcode 12

- packages/reactive_ble_mobile/android/src/main/kotlin/com/signify/hue/flutterreactiveble/PluginController.kt
- packages/reactive_ble_mobile/android/src/main/kotlin/com/signify/hue/flutterreactiveble/ReactiveBlePlugin.kt
- packages/reactive_ble_mobile/android/src/main/kotlin/com/signify/hue/flutterreactiveble/ble/ReactiveBleClient.kt
Without this, devices stay connected to detached native code and behave unexpectedly when reattached to flutter
> Deinitialize in onDetachedFromEngine on Android

- packages/reactive_ble_mobile/android/build.gradle
- packages/reactive_ble_mobile/android/src/main/kotlin/com/signify/hue/flutterreactiveble/ble/ReactiveBleClient.kt
RxAndroidBle 1.16.0 now supports enabling extended advertising (https://github.com/dariuszseweryn/RxAndroidBle/commit/4371b7832c1aaf328223f831d92b463dca039e85)
flutter_reactive_ble already supports extended advertising with iOS, so no changes are needed.
> Enable extended advertising on android

- README.md
- packages/flutter_reactive_ble/README.md
#524 tried to handle manifest merge issue for ble scan on Android 12.
But [RxAndroidBLE](https://github.com/dariuszseweryn/RxAndroidBle) which `flutter_reactive_ble` uses for bluetooth still has permissions on its [AndroidManifest.xml](https://github.com/dariuszseweryn/RxAndroidBle/blob/master/rxandroidble/src/main/AndroidManifest.xml). It causes merge issue when users try to scan bluetooth for `location` since `neverforlocation` already declared on that file.  
To get a scanresult for location Android 12, `neverforlocation` should be manullay removed using `tools:removed` and this PR is to mention it on README.md
> Update README.md to enable ble scan for location on Android 12

- packages/reactive_ble_platform_interface/lib/src/model/discovered_characteristic.dart
- packages/reactive_ble_platform_interface/lib/src/model/qualified_characteristic.dart
- packages/reactive_ble_platform_interface/lib/src/model/unit.dart
- packages/reactive_ble_platform_interface/lib/src/model/uuid.dart
Make operator == override parameters non-nullable. See dart-lang/linter#3441
Work towards dart-lang/sdk#51038.
> Make operator == override parameters non-nullable

- packages/reactive_ble_mobile/test/reactive_ble_platform_test.dart
`DEAD_CODE` will soon be a warning which will start to fail `dart analyze` (without `--fatal-warnings=false`).
This change will prevent that warning from being reported.
> Remove dead code from reactive_ble_platform_test

- .swiftlint.yml
- packages/reactive_ble_mobile/ios/Classes/BleData extras/BLEStatus.swift
- packages/reactive_ble_mobile/ios/Classes/BleData extras/FailureCodes.swift
- packages/reactive_ble_mobile/ios/Classes/Plugin/Common/EventSink.swift
- packages/reactive_ble_mobile/ios/Classes/Plugin/PluginController.swift
- packages/reactive_ble_mobile/ios/Classes/Plugin/SwiftReactiveBlePlugin.swift
- packages/reactive_ble_mobile/ios/Classes/ReactiveBle/Central.swift
- packages/reactive_ble_mobile/ios/Classes/ReactiveBle/CentralManagerDelegate.swift
- packages/reactive_ble_mobile/ios/Classes/ReactiveBle/Tasks/CharacteristicNotify/CharacteristicNotifyTaskController.swift
- packages/reactive_ble_mobile/ios/Classes/ReactiveBle/Tasks/Connect/ConnectTaskController.swift
- packages/reactive_ble_mobile/ios/Classes/ReactiveBle/Tasks/Connect/ConnectTaskSpec.swift
- packages/reactive_ble_mobile/ios/Classes/ReactiveBle/Tasks/PeripheralTaskRegistry/PeripheralTaskRegistry.swift
Initial stab at formatting as discussed in #760 
This is not integrated in CI/CD yet, but only tries to do light formatting to get started.
cc @remonh87 @Taym95
> swiftlint config and inital formatting pass

- example/pubspec.yaml
- packages/flutter_reactive_ble/pubspec.yaml
- packages/reactive_ble_mobile/pubspec.yaml
Update required version of the plugin to fix 5.3.0 release.
Fixes https://github.com/PhilipsHue/flutter_reactive_ble/issues/835
This is annoying issue and we had it quite often in Plus Plugins earlier before.
> Use proper platform_interface dependency version

- packages/flutter_reactive_ble/lib/src/reactive_ble.dart
- Previous code would create a broadcastStream from a normal stream (created by Repeater). When this is done, the source stream subscription needs to be explicitly closed. This is usually done by implementing the onCancel callback from the asBroadcastStream method. This was not happening, so every call to connectedDeviceStream was creating a new subscription that was never closed.
- To fix the problem, this commit uses the Repeater.broadcast constructor which already returns a broadcast stream and also closes the source stream subscription when needed
> Fixes subscription to _deviceConnector.deviceConnectionStateUpdateStream leaking
